#!/usr/bin/env bash
# Sovereign Compute Sharing — JupyterHub Setup
#
# Portable setup script: run on any Linux gate with a GPU to stand up
# a multi-user JupyterHub with bioinformatics kernels.
#
# Usage: bash setup-jupyterhub.sh
#
# Prerequisites: curl, bash. Everything else is installed by this script.
# Installs to: ~/miniforge3 (conda), ~/jupyterhub (config + data)
# Does NOT require root for installation (root needed to add system users).

set -euo pipefail

CONDA_PREFIX="$HOME/miniforge3"
HUB_DIR="$HOME/jupyterhub"

echo "=== Sovereign Compute Sharing: JupyterHub Setup ==="
echo "Gate: $(hostname)"
echo "Date: $(date -u +%Y-%m-%dT%H:%M:%SZ)"
echo ""

# --- Step 1: Install miniforge if not present ---
if [ ! -d "$CONDA_PREFIX" ]; then
    echo "[1/5] Installing miniforge..."
    curl -L -o /tmp/miniforge.sh \
        "https://github.com/conda-forge/miniforge/releases/latest/download/Miniforge3-$(uname)-$(uname -m).sh"
    bash /tmp/miniforge.sh -b -p "$CONDA_PREFIX"
    rm /tmp/miniforge.sh
else
    echo "[1/5] miniforge already installed at $CONDA_PREFIX"
fi

eval "$("$CONDA_PREFIX/bin/conda" shell.bash hook)"

# --- Step 2: Create JupyterHub environment ---
if ! conda env list | grep -q "^jupyterhub "; then
    echo "[2/5] Creating JupyterHub environment..."
    mamba create -y -n jupyterhub python=3.12 \
        jupyterhub jupyterlab notebook \
        configurable-http-proxy jupyterhub-idle-culler
else
    echo "[2/5] JupyterHub environment already exists"
fi

# --- Step 3: Create bioinformatics Python kernel ---
if ! conda env list | grep -q "^bioinfo "; then
    echo "[3/5] Creating bioinformatics Python environment..."
    mamba create -y -n bioinfo python=3.12 \
        ipykernel scanpy anndata pandas numpy scipy \
        matplotlib seaborn scikit-learn
    mamba install -y -n bioinfo -c bioconda -c conda-forge \
        pydeseq2 snakemake-minimal biom-format

    conda activate bioinfo
    python -m ipykernel install --user \
        --name bioinfo \
        --display-name "Bioinformatics (Python 3.12)"
    conda deactivate
else
    echo "[3/5] bioinfo environment already exists"
fi

# --- Step 4: Create R bioinformatics kernel ---
if ! conda env list | grep -q "^r-bioinfo "; then
    echo "[4/5] Creating R bioinformatics environment..."
    mamba create -y -n r-bioinfo \
        r-base r-irkernel r-seurat r-ggplot2 r-dplyr r-tidyverse jupyter_client

    conda activate r-bioinfo
    Rscript -e "IRkernel::installspec(user = TRUE, name = 'r-bioinfo', displayname = 'R Bioinformatics')"
    conda deactivate
else
    echo "[4/5] r-bioinfo environment already exists"
fi

# --- Step 5: Create JupyterHub config ---
mkdir -p "$HUB_DIR/data"
mkdir -p "$HOME/notebooks"

ADMIN_USER="$(whoami)"

cat > "$HUB_DIR/jupyterhub_config.py" << PYEOF
"""
JupyterHub configuration for Sovereign Compute Sharing.
Generated by setup-jupyterhub.sh on $(hostname) at $(date -u +%Y-%m-%dT%H:%M:%SZ).
"""
import os

c = get_config()

c.JupyterHub.ip = '127.0.0.1'
c.JupyterHub.port = 8000

c.JupyterHub.authenticator_class = 'jupyterhub.auth.PAMAuthenticator'
c.Authenticator.admin_users = {'${ADMIN_USER}'}
c.Authenticator.allowed_users = {'${ADMIN_USER}'}

c.JupyterHub.spawner_class = 'jupyterhub.spawner.LocalProcessSpawner'
c.Spawner.default_url = '/lab'
c.Spawner.notebook_dir = '~/notebooks'
c.Spawner.mem_limit = '32G'
c.Spawner.cpu_limit = 8

conda_prefix = os.path.expanduser('~/miniforge3')
c.Spawner.environment = {
    'PATH': f'{conda_prefix}/envs/bioinfo/bin:{conda_prefix}/envs/r-bioinfo/bin:{conda_prefix}/bin:' + os.environ.get('PATH', ''),
}

c.JupyterHub.db_url = 'sqlite:///' + os.path.expanduser('~/jupyterhub/jupyterhub.sqlite')

c.JupyterHub.services = [
    {
        'name': 'idle-culler',
        'command': ['python3', '-m', 'jupyterhub_idle_culler', '--timeout=3600'],
    }
]

c.JupyterHub.load_roles = [
    {
        'name': 'idle-culler',
        'scopes': ['list:users', 'read:users:activity', 'read:servers', 'delete:servers'],
        'services': ['idle-culler'],
    }
]

c.JupyterHub.log_level = 'INFO'
PYEOF

echo ""
echo "=== Setup Complete ==="
echo "Gate:     $(hostname)"
echo "Admin:    ${ADMIN_USER}"
echo "Config:   ${HUB_DIR}/jupyterhub_config.py"
echo "Kernels:"
conda activate jupyterhub
jupyter kernelspec list
echo ""
echo "To start: bash ${HUB_DIR}/start.sh"
echo "To add users: sudo adduser <username> && edit jupyterhub_config.py allowed_users"
echo ""
echo "Security posture: LOCAL ONLY (127.0.0.1:8000)"
echo "For external access, set up a WireGuard/Tailscale tunnel."
